fields:
    widget_same_category:
        type: switch
        label: theme.newshub::lang.option.widget.current_buttons.same_category.label
        comment: theme.newshub::lang.option.widget.current_buttons.same_category.comment
        default: true
        span: left
    