fields:
    widget_posts_count:
        type: switch
        label: theme.newshub::lang.option.widget.current_categories.posts_count.label
        comment: theme.newshub::lang.option.widget.current_categories.posts_count.comment
        default: true
        span: left
    