fields:
    widget_html_content:
        type: codeeditor
        label: theme.newshub::lang.option.widget.html.content.label
        comment: theme.newshub::lang.option.widget.html.content.comment
        language: html
        required: true
