fields:
    widget_authors_count:
        type: number
        label: theme.newshub::lang.option.widget.authors.count.label
        comment: theme.newshub::lang.option.widget.authors.count.comment
        min: 1
        max: 30
        step: 1
        default: 5
        span: auto
    
    widget_authors_avatar:
        type: switch
        label: theme.newshub::lang.option.widget.authors.avatar.label
        comment: theme.newshub::lang.option.widget.authors.avatar.comment
        default: true
        span: left
    
    widget_authors_posts_count:
        type: switch
        label: theme.newshub::lang.option.widget.authors.posts_count.label
        comment: theme.newshub::lang.option.widget.authors.posts_count.comment
        default: true
        span: right

