fields:
    widget_category_count:
        type: number
        label: theme.newshub::lang.option.widget.categories.count.label
        comment: theme.newshub::lang.option.widget.categories.count.comment
        min: 1
        max: 30
        step: 1
        default: 5
        span: auto
    
    widget_category_posts_count:
        type: switch
        label: theme.newshub::lang.option.widget.categories.posts_count.label
        comment: theme.newshub::lang.option.widget.categories.posts_count.comment
        default: true
        span: left
    
    widget_category_empty:
        type: switch
        label: theme.newshub::lang.option.widget.categories.empty.label
        comment: theme.newshub::lang.option.widget.categories.empty.comment
        default: false
        span: right
