fields:
    widget_articles_type:
        type: dropdown
        label: theme.newshub::lang.option.widget.articles.articles_type.label
        comment: theme.newshub::lang.option.widget.articles.articles_type.comment
        showSearch: false
        options:
            latest: theme.newshub::lang.option.widget.articles.articles_type.latest
            random: theme.newshub::lang.option.widget.articles.articles_type.random
            by_author: theme.newshub::lang.option.widget.articles.articles_type.by_author
            by_category: theme.newshub::lang.option.widget.articles.articles_type.by_category
            by_tag: theme.newshub::lang.option.widget.articles.articles_type.by_tag
            by_views: theme.newshub::lang.option.widget.articles.articles_type.by_views
            by_unique_views: theme.newshub::lang.option.widget.articles.articles_type.by_unique_views
        span: left
    
    widget_articles_by_author:
        type: recordfinder
        label: theme.newshub::lang.option.widget.articles.articles_by_author.label
        comment: theme.newshub::lang.option.widget.articles.articles_by_author.comment
        list: ~/modules/backend/models/user/columns.yaml
        nameFrom: login
        modelClass: Backend\Models\User
        useRelation: false
        span: right
        required: true
        trigger:
            action: show
            condition: value[by_author]
            field: widget_articles_type
    
    widget_articles_by_category:
        type: recordfinder
        label: theme.newshub::lang.option.widget.articles.articles_by_category.label
        comment: theme.newshub::lang.option.widget.articles.articles_by_category.comment
        list: ~/plugins/rainlab/blog/models/category/columns.yaml
        modelClass: RainLab\Blog\Models\Category
        useRelation: false
        span: right
        required: true
        trigger:
            action: show
            condition: value[by_category]
            field: widget_articles_type
    
    widget_articles_by_tag:
        type: recordfinder
        label: theme.newshub::lang.option.widget.articles.articles_by_tag.label
        comment: theme.newshub::lang.option.widget.articles.articles_by_tag.comment
        list: ~/plugins/ratmd/bloghub/models/tag/columns.yaml
        modelClass: RatMD\BlogHub\Models\Tag
        useRelation: false
        span: right
        required: true
        trigger:
            action: show
            condition: value[by_tag]
            field: widget_articles_type
    
    widget_articles_count:
        type: number
        label: theme.newshub::lang.option.widget.articles.articles_count.label
        comment: theme.newshub::lang.option.widget.articles.articles_count.comment
        min: 1
        max: 30
        step: 1
        default: 5
        span: auto
