current_author:
    name: theme.newshub::lang.widget.current_author.label
    description: theme.newshub::lang.widget.current_author.comment
    fields:
        title:
            type: text
            label: theme.newshub::lang.widget.general.title.label
            comment: theme.newshub::lang.widget.general.title.comment
            span: left
        subtitle:
            type: text
            label: theme.newshub::lang.widget.general.subtitle.label
            comment: theme.newshub::lang.widget.general.subtitle.comment
            span: right
        avatar:
            type: switch
            label: theme.newshub::lang.widget.current_author.avatar.label
            comment: theme.newshub::lang.widget.current_author.avatar.comment
            default: true
            span: left
        aboutme:
            type: switch
            label: theme.newshub::lang.widget.current_author.aboutme.label
            comment: theme.newshub::lang.widget.current_author.aboutme.comment
            default: true
            span: right
        counter:
            type: switch
            label: theme.newshub::lang.widget.shared.counter.label
            comment: theme.newshub::lang.widget.shared.counter.comment
            default: true
            span: left
        favorite_category:
            type: switch
            label: theme.newshub::lang.widget.current_author.favorite_category.label
            comment: theme.newshub::lang.widget.current_author.favorite_category.comment
            default: true
            span: right

current_categories:
    name: theme.newshub::lang.widget.current_categories.label
    description: theme.newshub::lang.widget.current_categories.comment
    fields:
        title:
            type: text
            label: theme.newshub::lang.widget.general.title.label
            comment: theme.newshub::lang.widget.general.title.comment
            span: left
        subtitle:
            type: text
            label: theme.newshub::lang.widget.general.subtitle.label
            comment: theme.newshub::lang.widget.general.subtitle.comment
            span: right
        counter:
            type: switch
            label: theme.newshub::lang.widget.shared.counter.label
            comment: theme.newshub::lang.widget.shared.counter.comment
            default: true
            span: left

current_tags:
    name: theme.newshub::lang.widget.current_tags.label
    description: theme.newshub::lang.widget.current_tags.comment
    fields:
        title:
            type: text
            label: theme.newshub::lang.widget.general.title.label
            comment: theme.newshub::lang.widget.general.title.comment
            span: left
        subtitle:
            type: text
            label: theme.newshub::lang.widget.general.subtitle.label
            comment: theme.newshub::lang.widget.general.subtitle.comment
            span: right
        counter:
            type: switch
            label: theme.newshub::lang.widget.shared.counter.label
            comment: theme.newshub::lang.widget.shared.counter.comment
            default: true
            span: left

current_pagination:
    name: theme.newshub::lang.widget.current_pagination.label
    description: theme.newshub::lang.widget.current_pagination.comment
    fields:
        title:
            type: text
            label: theme.newshub::lang.widget.general.title.label
            comment: theme.newshub::lang.widget.general.title.comment
            span: left
        subtitle:
            type: text
            label: theme.newshub::lang.widget.general.subtitle.label
            comment: theme.newshub::lang.widget.general.subtitle.comment
            span: right
        same_category:
            type: switch
            label: theme.newshub::lang.widget.current_pagination.same_category.label
            comment: theme.newshub::lang.widget.current_pagination.same_category.comment
            default: true
            span: left

current_related:
    name: theme.newshub::lang.widget.current_related.label
    description: theme.newshub::lang.widget.current_related.comment
    fields:
        title:
            type: text
            label: theme.newshub::lang.widget.general.title.label
            comment: theme.newshub::lang.widget.general.title.comment
            span: left
        subtitle:
            type: text
            label: theme.newshub::lang.widget.general.subtitle.label
            comment: theme.newshub::lang.widget.general.subtitle.comment
            span: right
        number:
            type: number
            label: theme.newshub::lang.widget.shared.number.label
            comment: theme.newshub::lang.widget.shared.number.comment
            default: 5
            span: left

blog_posts:
    name: theme.newshub::lang.widget.blog_posts.label
    description: theme.newshub::lang.widget.blog_posts.comment
    fields:
        title:
            type: text
            label: theme.newshub::lang.widget.general.title.label
            comment: theme.newshub::lang.widget.general.title.comment
            span: left
        subtitle:
            type: text
            label: theme.newshub::lang.widget.general.subtitle.label
            comment: theme.newshub::lang.widget.general.subtitle.comment
            span: right
        list_type:
            type: dropdown 
            label: theme.newshub::lang.widget.blog_posts.list_type.label
            comment: theme.newshub::lang.widget.blog_posts.list_type.comment
            showSearch: false
            default: latest
            options:
                latest: theme.newshub::lang.widget.blog_posts.list_type.latest
                random: theme.newshub::lang.widget.blog_posts.list_type.random
                by_author: theme.newshub::lang.widget.blog_posts.list_type.by_author
                by_category: theme.newshub::lang.widget.blog_posts.list_type.by_category
                by_tag: theme.newshub::lang.widget.blog_posts.list_type.by_tag
                by_comments: theme.newshub::lang.widget.blog_posts.list_type.by_comments
                by_views: theme.newshub::lang.widget.blog_posts.list_type.by_views
                by_visitors: theme.newshub::lang.widget.blog_posts.list_type.by_visitors
            span: left
        list_author:
            type: recordfinder
            label: theme.newshub::lang.widget.blog_posts.list_author.label
            comment: theme.newshub::lang.widget.blog_posts.list_author.comment
            list: ~/modules/backend/models/user/columns.yaml
            nameFrom: login
            modelClass: Backend\Models\User
            useRelation: false
            required: true
            trigger:
                action: show
                condition: value[by_author]
                field: list_type
            span: right
        list_category:
            type: recordfinder
            label: theme.newshub::lang.widget.blog_posts.list_category.label
            comment: theme.newshub::lang.widget.blog_posts.list_category.comment
            list: ~/plugins/rainlab/blog/models/category/columns.yaml
            modelClass: RainLab\Blog\Models\Category
            useRelation: false
            required: true
            trigger:
                action: show
                condition: value[by_category]
                field: list_type
            span: right
        list_tag:
            type: recordfinder
            label: theme.newshub::lang.widget.blog_posts.list_tag.label
            comment: theme.newshub::lang.widget.blog_posts.list_tag.comment
            list: ~/plugins/ratmd/bloghub/models/tag/columns.yaml
            modelClass: RatMD\BlogHub\Models\Tag
            useRelation: false
            required: true
            trigger:
                action: show
                condition: value[by_tag]
                field: list_type
            span: right
        number:
            type: number
            label: theme.newshub::lang.widget.shared.number.label
            comment: theme.newshub::lang.widget.shared.number.comment
            default: 5
            span: left

blog_comments:
    name: theme.newshub::lang.widget.blog_comments.label
    description: theme.newshub::lang.widget.blog_comments.comment
    fields:
        title:
            type: text
            label: theme.newshub::lang.widget.general.title.label
            comment: theme.newshub::lang.widget.general.title.comment
            span: left
        subtitle:
            type: text
            label: theme.newshub::lang.widget.general.subtitle.label
            comment: theme.newshub::lang.widget.general.subtitle.comment
            span: right
        number:
            type: number
            label: theme.newshub::lang.widget.shared.number.label
            comment: theme.newshub::lang.widget.shared.number.comment
            default: 5
            span: left
        avatars:
            type: switch
            label: theme.newshub::lang.widget.shared.avatars.label
            comment: theme.newshub::lang.widget.shared.avatars.comment
            default: false
            span: left

blog_authors:
    name: theme.newshub::lang.widget.blog_authors.label
    description: theme.newshub::lang.widget.blog_authors.comment
    fields:
        title:
            type: text
            label: theme.newshub::lang.widget.general.title.label
            comment: theme.newshub::lang.widget.general.title.comment
            span: left
        subtitle:
            type: text
            label: theme.newshub::lang.widget.general.subtitle.label
            comment: theme.newshub::lang.widget.general.subtitle.comment
            span: right
        number:
            type: number
            label: theme.newshub::lang.widget.shared.number.label
            comment: theme.newshub::lang.widget.shared.number.comment
            default: 5
            span: left
        counter:
            type: switch
            label: theme.newshub::lang.widget.shared.counter.label
            comment: theme.newshub::lang.widget.shared.counter.comment
            default: true
            span: left
        avatars:
            type: switch
            label: theme.newshub::lang.widget.shared.avatars.label
            comment: theme.newshub::lang.widget.shared.avatars.comment
            default: true
            span: right

blog_categories:
    name: theme.newshub::lang.widget.blog_categories.label
    description: theme.newshub::lang.widget.blog_categories.comment
    fields:
        title:
            type: text
            label: theme.newshub::lang.widget.general.title.label
            comment: theme.newshub::lang.widget.general.title.comment
            span: left
        subtitle:
            type: text
            label: theme.newshub::lang.widget.general.subtitle.label
            comment: theme.newshub::lang.widget.general.subtitle.comment
            span: right
        number:
            type: number
            label: theme.newshub::lang.widget.shared.number.label
            comment: theme.newshub::lang.widget.shared.number.comment
            default: 5
            span: left
        counter:
            type: switch
            label: theme.newshub::lang.widget.shared.counter.label
            comment: theme.newshub::lang.widget.shared.counter.comment
            default: true
            span: left
        empty:
            type: switch
            label: theme.newshub::lang.widget.blog_categories.empty.label
            comment: theme.newshub::lang.widget.blog_categories.empty.comment
            default: true
            span: right

blog_tags:
    name: theme.newshub::lang.widget.blog_tags.label
    description: theme.newshub::lang.widget.blog_tags.comment
    fields:
        title:
            type: text
            label: theme.newshub::lang.widget.general.title.label
            comment: theme.newshub::lang.widget.general.title.comment
            span: left
        subtitle:
            type: text
            label: theme.newshub::lang.widget.general.subtitle.label
            comment: theme.newshub::lang.widget.general.subtitle.comment
            span: right
        number:
            type: number
            label: theme.newshub::lang.widget.shared.number.label
            comment: theme.newshub::lang.widget.shared.number.comment
            default: 5
            span: left
        counter:
            type: switch
            label: theme.newshub::lang.widget.shared.counter.label
            comment: theme.newshub::lang.widget.shared.counter.comment
            default: true
            span: left
        promoted:
            type: switch
            label: theme.newshub::lang.widget.blog_tags.promoted.label
            comment: theme.newshub::lang.widget.blog_tags.promoted.comment
            default: true
            span: right

static_menu:
    name: theme.newshub::lang.widget.static_menu.label
    description: theme.newshub::lang.widget.static_menu.comment
    fields:
        title:
            type: text
            label: theme.newshub::lang.widget.general.title.label
            comment: theme.newshub::lang.widget.general.title.comment
            span: left
        subtitle:
            type: text
            label: theme.newshub::lang.widget.general.subtitle.label
            comment: theme.newshub::lang.widget.general.subtitle.comment
            span: right
        menu_code:
            type: text
            label: theme.newshub::lang.widget.static_menu.menu_code.label
            comment: theme.newshub::lang.widget.static_menu.menu_code.comment
            required: true
            span: left

content:
    name: theme.newshub::lang.widget.content.label
    description: theme.newshub::lang.widget.content.comment
    fields:
        title:
            type: text
            label: theme.newshub::lang.widget.general.title.label
            comment: theme.newshub::lang.widget.general.title.comment
            span: left
        subtitle:
            type: text
            label: theme.newshub::lang.widget.general.subtitle.label
            comment: theme.newshub::lang.widget.general.subtitle.comment
            span: right
        content:
            type: richeditor
            label: theme.newshub::lang.widget.shared.content.label
            comment: theme.newshub::lang.widget.shared.content.comment

html:
    name: theme.newshub::lang.widget.html.label
    description: theme.newshub::lang.widget.html.comment
    fields:
        title:
            type: text
            label: theme.newshub::lang.widget.general.title.label
            comment: theme.newshub::lang.widget.general.title.comment
            span: left
        subtitle:
            type: text
            label: theme.newshub::lang.widget.general.subtitle.label
            comment: theme.newshub::lang.widget.general.subtitle.comment
            span: right
        content:
            type: codeeditor
            label: theme.newshub::lang.widget.shared.content.label
            comment: theme.newshub::lang.widget.shared.content.comment
            language: html

image:
    name: theme.newshub::lang.widget.image.label
    description: theme.newshub::lang.widget.image.comment
    fields:
        title:
            type: text
            label: theme.newshub::lang.widget.general.title.label
            comment: theme.newshub::lang.widget.general.title.comment
            span: left
        subtitle:
            type: text
            label: theme.newshub::lang.widget.general.subtitle.label
            comment: theme.newshub::lang.widget.general.subtitle.comment
            span: right
        image:
            type: mediafinder
            label: theme.newshub::lang.widget.image.image.label
            comment: theme.newshub::lang.widget.image.image.comment
            mode: image
            maxItems: 1
        content:
            type: textarea
            label: theme.newshub::lang.widget.shared.content.label
            comment: theme.newshub::lang.widget.shared.content.comment
