
fields:
    widget_type:
        type: dropdown
        label: theme.newshub::lang.option.sidebars.widget_type.label
        comment: theme.newshub::lang.option.sidebars.widget_type.comment
        showSearch: false
        options:
            current_author: theme.newshub::lang.option.sidebars.widget_type.current_author
            current_categories: theme.newshub::lang.option.sidebars.widget_type.current_categories
            current_tags: theme.newshub::lang.option.sidebars.widget_type.current_tags
            current_buttons: theme.newshub::lang.option.sidebars.widget_type.current_buttons
            articles: theme.newshub::lang.option.sidebars.widget_type.articles
            authors: theme.newshub::lang.option.sidebars.widget_type.author
            categories: theme.newshub::lang.option.sidebars.widget_type.category
            tags: theme.newshub::lang.option.sidebars.widget_type.tags
            static_menu: theme.newshub::lang.option.sidebars.widget_type.static_menu
            content: theme.newshub::lang.option.sidebars.widget_type.content
            html: theme.newshub::lang.option.sidebars.widget_type.html
        span: left
    
    widget_title:
        type: text
        label: theme.newshub::lang.option.sidebars.widget_title.label
        comment: theme.newshub::lang.option.sidebars.widget_title.comment
        span: right
    
    widget_subtitle:
        type: text
        label: theme.newshub::lang.option.sidebars.widget_subtitle.label
        comment: theme.newshub::lang.option.sidebars.widget_subtitle.comment
        span: right
    
    __widget_options_ruler:
        type: ruler
    
    ##############################
    ### WIDGET: CURRENT AUTHOR ###
    ##############################
    widget_current_author:
        type: nestedform
        showPanel: false
        form: ~/themes/newshub/config/widgets/current-author.yaml
        trigger:
            action: show
            condition: value[current_author]
            field: widget_type
    
    ##################################
    ### WIDGET: CURRENT CATEGORIES ###
    ##################################
    widget_current_categories:
        type: nestedform
        showPanel: false
        form: ~/themes/newshub/config/widgets/current-categories.yaml
        trigger:
            action: show
            condition: value[current_categories]
            field: widget_type
    
    ############################
    ### WIDGET: CURRENT TAGS ###
    ############################
    widget_current_tags:
        type: nestedform
        showPanel: false
        form: ~/themes/newshub/config/widgets/current-tags.yaml
        trigger:
            action: show
            condition: value[current_tags]
            field: widget_type
    
    #######################################
    ### WIDGET: NEXT | PREVIOUS BUTTONS ###
    #######################################
    widget_current_buttons:
        type: nestedform
        showPanel: false
        form: ~/themes/newshub/config/widgets/current-buttons.yaml
        trigger:
            action: show
            condition: value[current_buttons]
            field: widget_type

    #############################
    ### WIDGET: LIST ARTICLES ###
    #############################
    widget_articles:
        type: nestedform
        showPanel: false
        form: ~/themes/newshub/config/widgets/list-articles.yaml
        trigger:
            action: show
            condition: value[articles]
            field: widget_type

    ############################
    ### WIDGET: LIST AUTHORS ###
    ############################
    widget_authors:
        type: nestedform
        showPanel: false
        form: ~/themes/newshub/config/widgets/list-authors.yaml
        trigger:
            action: show
            condition: value[authors]
            field: widget_type

    ###############################
    ### WIDGET: LIST CATEGORIES ###
    ###############################
    widget_categories:
        type: nestedform
        showPanel: false
        form: ~/themes/newshub/config/widgets/list-categories.yaml
        trigger:
            action: show
            condition: value[categories]
            field: widget_type

    #########################
    ### WIDGET: LIST TAGS ###
    #########################
    widget_tags:
        type: nestedform
        showPanel: false
        form: ~/themes/newshub/config/widgets/list-tags.yaml
        trigger:
            action: show
            condition: value[tags]
            field: widget_type

    ###########################
    ### WIDGET: STATIC MENU ###
    ###########################
    widget_static_menu:
        type: nestedform
        showPanel: false
        form: ~/themes/newshub/config/widgets/static-menu.yaml
        trigger:
            action: show
            condition: value[static_menu]
            field: widget_type

    #######################
    ### WIDGET: CONTENT ###
    #######################
    widget_content:
        type: nestedform
        showPanel: false
        form: ~/themes/newshub/config/widgets/content.yaml
        trigger:
            action: show
            condition: value[content]
            field: widget_type

    #########################
    ### WIDGET: HTML CODE ###
    #########################
    widget_html:
        type: nestedform
        showPanel: false
        form: ~/themes/newshub/config/widgets/html.yaml
        trigger:
            action: show
            condition: value[html]
            field: widget_type
