tabs:
    fields:
        __brand_section:
            tab: theme.newshub::lang.option.tabs.general
            type: section
            label: theme.newshub::lang.option.sections.brand
        site_name:
            tab: theme.newshub::lang.option.tabs.general
            type: text
            label: theme.newshub::lang.option.site_name.label
            comment: theme.newshub::lang.option.site_name.comment
            default: NewsHub
        site_logo:
            tab: theme.newshub::lang.option.tabs.general
            type: fileupload
            mode: image
            label: theme.newshub::lang.option.site_logo.label
            comment: theme.newshub::lang.option.site_logo.comment
            imageHeight: 60
            maxFiles: 1
            useCaption: false
            thumbOptions: false
            span: left
        site_logo_inverted:
            tab: theme.newshub::lang.option.tabs.general
            type: fileupload
            mode: image
            label: theme.newshub::lang.option.site_logo_inverted.label
            comment: theme.newshub::lang.option.site_logo_inverted.comment
            imageHeight: 60
            maxFiles: 1
            useCaption: false
            thumbOptions: false
            span: right

        __development_section:
            tab: theme.newshub::lang.option.tabs.general
            type: section
            label: theme.newshub::lang.option.sections.development
        show_demo:
            tab: theme.newshub::lang.option.tabs.general
            type: switch
            label: theme.newshub::lang.option.show_demo.label
            comment: theme.newshub::lang.option.show_demo.comment
            default: true
            
        __color_scheme_section:
            tab: theme.newshub::lang.option.tabs.appearance
            type: section
            label: theme.newshub::lang.option.sections.color_scheme
        dark_scheme:
            tab: theme.newshub::lang.option.tabs.appearance
            type: switch
            label: theme.newshub::lang.option.dark_scheme.label
            comment: theme.newshub::lang.option.dark_scheme.comment
            default: false
        dark_header:
            tab: theme.newshub::lang.option.tabs.appearance
            type: switch
            label: theme.newshub::lang.option.dark_header.label
            comment: theme.newshub::lang.option.dark_header.comment
            default: false
        dark_footer:
            tab: theme.newshub::lang.option.tabs.appearance
            type: switch
            label: theme.newshub::lang.option.dark_footer.label
            comment: theme.newshub::lang.option.dark_footer.comment
            default: false

        __color_palette_section:
            tab: theme.newshub::lang.option.tabs.appearance
            type: section
            label: theme.newshub::lang.option.sections.color_palette
        color_primary:
            tab: theme.newshub::lang.option.tabs.appearance
            type: colorpicker
            label: theme.newshub::lang.option.color_primary.label
            allowEmpty: false
            default: '#0d6efd'
            availableColors:
                - '#0d6efd'
                - '#6610f2'
                - '#6f42c1'
                - '#d63384'
                - '#dc3545'
                - '#fd7e14'
                - '#ffc107'
                - '#198754'
                - '#20c997'
                - '#0dcaf0'
        color_secondary:
            tab: theme.newshub::lang.option.tabs.appearance
            type: colorpicker
            label: theme.newshub::lang.option.color_secondary.label
            allowEmpty: false
            default: '#6c757d'
            availableColors:
                - '#0d6efd'
                - '#6610f2'
                - '#6f42c1'
                - '#d63384'
                - '#dc3545'
                - '#fd7e14'
                - '#ffc107'
                - '#198754'
                - '#20c997'
                - '#0dcaf0'
        color_success:
            tab: theme.newshub::lang.option.tabs.appearance
            type: colorpicker
            label: theme.newshub::lang.option.color_success.label
            allowEmpty: false
            default: '#198754'
            availableColors:
                - '#0d6efd'
                - '#6610f2'
                - '#6f42c1'
                - '#d63384'
                - '#dc3545'
                - '#fd7e14'
                - '#ffc107'
                - '#198754'
                - '#20c997'
                - '#0dcaf0'
        color_info:
            tab: theme.newshub::lang.option.tabs.appearance
            type: colorpicker
            label: theme.newshub::lang.option.color_info.label
            allowEmpty: false
            default: '#0dcaf0'
            availableColors:
                - '#0d6efd'
                - '#6610f2'
                - '#6f42c1'
                - '#d63384'
                - '#dc3545'
                - '#fd7e14'
                - '#ffc107'
                - '#198754'
                - '#20c997'
                - '#0dcaf0'
        color_warning:
            tab: theme.newshub::lang.option.tabs.appearance
            type: colorpicker
            label: theme.newshub::lang.option.color_warning.label
            allowEmpty: false
            default: '#ffc107'
            availableColors:
                - '#0d6efd'
                - '#6610f2'
                - '#6f42c1'
                - '#d63384'
                - '#dc3545'
                - '#fd7e14'
                - '#ffc107'
                - '#198754'
                - '#20c997'
                - '#0dcaf0'
        color_danger:
            tab: theme.newshub::lang.option.tabs.appearance
            type: colorpicker
            label: theme.newshub::lang.option.color_danger.label
            allowEmpty: false
            default: '#dc3545'
            availableColors:
                - '#0d6efd'
                - '#6610f2'
                - '#6f42c1'
                - '#d63384'
                - '#dc3545'
                - '#fd7e14'
                - '#ffc107'
                - '#198754'
                - '#20c997'
                - '#0dcaf0'
        
        __main_header_section:
            tab: theme.newshub::lang.option.tabs.header
            type: section
            label: theme.newshub::lang.option.sections.main_header
        navbar_style:
            tab: theme.newshub::lang.option.tabs.header
            type: dropdown
            label: theme.newshub::lang.option.navbar_style.label
            comment: theme.newshub::lang.option.navbar_style.comment
            default: condensed
            showSearch: false
            span: auto
            options:
                condensed: theme.newshub::lang.option.navbar_style.condensed
                extended: theme.newshub::lang.option.navbar_style.extended
        sticky_header:
            tab: theme.newshub::lang.option.tabs.header
            type: switch
            label: theme.newshub::lang.option.sticky_header.label
            comment: theme.newshub::lang.option.sticky_header.comment
            default: false
        color_switch_top:
            tab: theme.newshub::lang.option.tabs.header
            type: switch
            label: theme.newshub::lang.option.color_switch.label
            comment: theme.newshub::lang.option.color_switch.comment
            default: false
        languages_menu_top:
            tab: theme.newshub::lang.option.tabs.header
            type: switch
            label: theme.newshub::lang.option.languages_menu.label
            comment: theme.newshub::lang.option.languages_menu.comment
            default: false
        search_button:
            tab: theme.newshub::lang.option.tabs.header
            type: switch
            label: theme.newshub::lang.option.search_button.label
            comment: theme.newshub::lang.option.search_button.comment
            default: false
            trigger:
                action: show
                condition: value[extended]
                field: navbar_style
#        user_button:
#            tab: theme.newshub::lang.option.tabs.header
#            type: switch
#            label: theme.newshub::lang.option.user_button.label
#            comment: theme.newshub::lang.option.user_button.comment
#            default: false
#            trigger:
#                action: show
#                condition: value[extended]
#                field: navbar_style
        
        __hero_area_section:
            tab: theme.newshub::lang.option.tabs.header
            type: section
            label: theme.newshub::lang.option.sections.hero_area
        hero_slider:
            tab: theme.newshub::lang.option.tabs.header
            type: switch
            label: theme.newshub::lang.option.hero_slider.label
            comment: theme.newshub::lang.option.hero_slider.comment
            default: true
            span: left
        hero_slider_category:
            tab: theme.newshub::lang.option.tabs.header
            type: recordfinder
            label: theme.newshub::lang.option.hero_slider_category.label
            comment: theme.newshub::lang.option.hero_slider_category.comment
            list: ~/plugins/rainlab/blog/models/category/columns.yaml
            modelClass: RainLab\Blog\Models\Category
            useRelation: false
            span: right

        __posts_section:
            tab: theme.newshub::lang.option.tabs.content
            type: section
            label: theme.newshub::lang.option.sections.posts
        view_counter:
            tab: theme.newshub::lang.option.tabs.content
            type: switch
            label: theme.newshub::lang.option.view_counter.label
            comment: theme.newshub::lang.option.view_counter.comment
            default: true
            span: left
        __localization_section:
            tab: theme.newshub::lang.option.tabs.content
            type: section
            label: theme.newshub::lang.option.sections.localization
        datetime_format:
            tab: theme.newshub::lang.option.tabs.content
            type: text
            label: theme.newshub::lang.option.datetime_format.label
            default: D., j. F Y - H:i
            comment: theme.newshub::lang.option.datetime_format.comment
            commentHtml: true
            span: left
        short_datetime_format:
            tab: theme.newshub::lang.option.tabs.content
            type: text
            label: theme.newshub::lang.option.short_datetime_format.label
            default: M. j, Y - H:i
            comment: theme.newshub::lang.option.datetime_format.comment
            commentHtml: true
            span: right
        
        sidebar:
            tab: theme.newshub::lang.option.tabs.sidebars
            type: dropdown
            label: theme.newshub::lang.option.sidebars.label
            comment: theme.newshub::lang.option.sidebars.comment
            showSearch: false
            emptyOption: theme.newshub::lang.option.sidebars.emptyOption
            options:
                home: theme.newshub::lang.option.sidebars.home
                page: theme.newshub::lang.option.sidebars.page
                post: theme.newshub::lang.option.sidebars.post
        __sidebar_config_section:
            tab: theme.newshub::lang.option.tabs.sidebars
            type: section
            label: theme.newshub::lang.option.sections.sidebar
        __sidebar_hint:
            tab: theme.newshub::lang.option.tabs.sidebars
            type: hint
            mode: tip
            label: theme.newshub::lang.option.sidebars.hint.label
            comment: theme.newshub::lang.option.sidebars.hint.comment
            trigger:
                action: hide
                condition: value[home][page][post]
                field: sidebar
        sidebar_home:
            tab: theme.newshub::lang.option.tabs.sidebars
            type: repeater
            label: theme.newshub::lang.option.sidebars.home
            titleFrom: widget_title
            displayMode: builder
            prompt: theme.newshub::lang.option.sidebars.prompt
            form: ~/themes/newshub/config/sidebars/homepage.yaml
            trigger:
                action: show
                condition: value[home]
                field: sidebar
        sidebar_page:
            tab: theme.newshub::lang.option.tabs.sidebars
            type: repeater
            label: theme.newshub::lang.option.sidebars.page
            titleFrom: widget_title
            displayMode: builder
            prompt: theme.newshub::lang.option.sidebars.prompt
            form: ~/themes/newshub/config/sidebars/page.yaml
            trigger:
                action: show
                condition: value[page]
                field: sidebar
        sidebar_post:
            tab: theme.newshub::lang.option.tabs.sidebars
            type: repeater
            label: theme.newshub::lang.option.sidebars.post
            titleFrom: widget_title
            displayMode: builder
            prompt: theme.newshub::lang.option.sidebars.prompt
            form: ~/themes/newshub/config/sidebars/post.yaml
            trigger:
                action: show
                condition: value[post]
                field: sidebar
            
        __main_footer_section:
            tab: theme.newshub::lang.option.tabs.footer
            type: section
            label: theme.newshub::lang.option.sections.main_footer
        color_switch_bottom:
            tab: theme.newshub::lang.option.tabs.footer
            type: switch
            label: theme.newshub::lang.option.color_switch.label
            comment: theme.newshub::lang.option.color_switch.comment
            default: false
        languages_menu_bottom:
            tab: theme.newshub::lang.option.tabs.footer
            type: switch
            label: theme.newshub::lang.option.languages_menu.label
            comment: theme.newshub::lang.option.languages_menu.comment
            default: false
        to_top_button:
            tab: theme.newshub::lang.option.tabs.footer
            type: switch
            label: theme.newshub::lang.option.to_top_button.label
            comment: theme.newshub::lang.option.to_top_button.comment
            default: true
        copyright_text_left:
            tab: theme.newshub::lang.option.tabs.footer
            type: textarea
            label: theme.newshub::lang.option.copyright_text_left.label
            comment: theme.newshub::lang.option.copyright_text_left.comment
            default: >
                Copyright {year} &copy; {site_name}

                All rights reserved
            span: left
        copyright_text_right:
            tab: theme.newshub::lang.option.tabs.footer
            type: textarea
            label: theme.newshub::lang.option.copyright_text_right.label
            comment: theme.newshub::lang.option.copyright_text_right.comment
            default: >
                NewsHub Template by [rat.md](https://rat.md)

                Designed with [Bootstrap 5.2](https:getbootstrap.com)
            span: right